### ISSUE TITLE
EPIC 01 - Setup Database

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread#11]
- [x] [Users Table](https://github.com/zachholcomb/good_bread/projects/1#card-44442947)
 - [x] [Items Table](https://github.com/zachholcomb/good_bread/projects/1#card-44442957)
 - [ ] [Subscriptions Table](https://github.com/zachholcomb/good_bread/projects/1#card-44442971)
 - [ ] [ Shipments Table](https://github.com/zachholcomb/good_bread/projects/1#card-44442977)
 - [ ] [ShipmentItems Table](https://github.com/zachholcomb/good_bread/projects/1#card-44442986)
 - [ ] [Set up relationships](https://github.com/zachholcomb/good_bread/projects/1#card-44443661)
