### ISSUE TITLE
Set Up Relationships

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread#6]
Set up the following relationships:
- [ ] Users to Subscriptions: Many to Many
- [ ] Users to Shipments: Many to Many 
- [ ] Shipments to Subscriptions: Many to One
- [ ] Shipments to Items: Many to Many
